<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\CatUaaController;
use App\Http\Controllers\Api\CatDgsegEfController;
use App\Http\Controllers\Api\CatEntregaController;
use App\Http\Controllers\Api\AuditoriasController;
use App\Http\Controllers\Api\CatClaveAccionController;
use App\Http\Controllers\Api\CatCuentaPublicaController;
use App\Http\Controllers\Api\CatEnteDeLaAccionController;
use App\Http\Controllers\Api\CatUaasAuditoriasController;
use App\Http\Controllers\Api\CatEnteFiscalizadoController;
use App\Http\Controllers\Api\CatTipoDeAuditoriaController;
use App\Http\Controllers\Api\CatSiglasTipoAccionController;
use App\Http\Controllers\Api\CatAuditoriaEspecialController;
use App\Http\Controllers\Api\CatDgsegEfsAuditoriasController;
use App\Http\Controllers\Api\CatEntregasAuditoriasController;
use App\Http\Controllers\Api\CatClaveAccionsAuditoriasController;
use App\Http\Controllers\Api\CatSiglasAuditoriaEspecialController;
use App\Http\Controllers\Api\CatCuentaPublicasAuditoriasController;
use App\Http\Controllers\Api\CatEnteDeLaAccionsAuditoriasController;
use App\Http\Controllers\Api\CatEnteFiscalizadosAuditoriasController;
use App\Http\Controllers\Api\CatTipoDeAuditoriasAuditoriasController;
use App\Http\Controllers\Api\CatAuditoriaEspecialsAuditoriasController;
use App\Http\Controllers\Api\CatSiglasTipoAccionesAuditoriasController;
use App\Http\Controllers\Api\CatSiglasAuditoriaEspecialsAuditoriasController;

/*
|--------------------------------------------------------------------------
| Api Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

Route::name('api.')
    ->prefix('api')
    ->group(function () {
        Route::post('/login', [AuthController::class, 'login'])->name(
            'api.login'
        );

        Route::middleware('auth:sanctum')->group(function () {
            Route::get('/cat-dgseg-efs/{cat-dgseg-ef}/all-auditorias', [
                CatDgsegEfsAuditoriasController::class,
                'index',
            ])->name('cat-dgseg-efs.all-auditorias.index');

            Route::post('/cat-dgseg-efs/{cat-dgseg-ef}/all-auditorias', [
                CatDgsegEfsAuditoriasController::class,
                'store',
            ])->name('cat-dgseg-efs.all-auditorias.store');

            Route::get('/cat-dgseg-efs', [
                CatDgsegEfController::class,
                'index',
            ])->name('cat-dgseg-efs.index');

            Route::post('/cat-dgseg-efs', [
                CatDgsegEfController::class,
                'store',
            ])->name('cat-dgseg-efs.store');

            Route::get('/cat-dgseg-efs/{catDgsegEf}', [
                CatDgsegEfController::class,
                'show',
            ])->name('cat-dgseg-efs.show');

            Route::put('/cat-dgseg-efs/{catDgsegEf}', [
                CatDgsegEfController::class,
                'update',
            ])->name('cat-dgseg-efs.update');

            Route::delete('/cat-dgseg-efs/{catDgsegEf}', [
                CatDgsegEfController::class,
                'destroy',
            ])->name('cat-dgseg-efs.destroy');

            Route::get('/cat-clave-accions/{cat-clave-accion}/all-auditorias', [
                CatClaveAccionsAuditoriasController::class,
                'index',
            ])->name('cat-clave-accions.all-auditorias.index');

            Route::post(
                '/cat-clave-accions/{cat-clave-accion}/all-auditorias',
                [CatClaveAccionsAuditoriasController::class, 'store']
            )->name('cat-clave-accions.all-auditorias.store');

            Route::get('/cat-clave-accions', [
                CatClaveAccionController::class,
                'index',
            ])->name('cat-clave-accions.index');

            Route::post('/cat-clave-accions', [
                CatClaveAccionController::class,
                'store',
            ])->name('cat-clave-accions.store');

            Route::get('/cat-clave-accions/{catClaveAccion}', [
                CatClaveAccionController::class,
                'show',
            ])->name('cat-clave-accions.show');

            Route::put('/cat-clave-accions/{catClaveAccion}', [
                CatClaveAccionController::class,
                'update',
            ])->name('cat-clave-accions.update');

            Route::delete('/cat-clave-accions/{catClaveAccion}', [
                CatClaveAccionController::class,
                'destroy',
            ])->name('cat-clave-accions.destroy');

            Route::get('/cat-clave-accions/{cat-clave-accion}/all-auditorias', [
                CatClaveAccionsAuditoriasController::class,
                'index',
            ])->name('cat-clave-accions.all-auditorias.index');

            Route::post(
                '/cat-clave-accions/{cat-clave-accion}/all-auditorias',
                [CatClaveAccionsAuditoriasController::class, 'store']
            )->name('cat-clave-accions.all-auditorias.store');

            Route::get('/cat-clave-accions', [
                CatClaveAccionController::class,
                'index',
            ])->name('cat-clave-accions.index');

            Route::post('/cat-clave-accions', [
                CatClaveAccionController::class,
                'store',
            ])->name('cat-clave-accions.store');

            Route::get('/cat-clave-accions/{catClaveAccion}', [
                CatClaveAccionController::class,
                'show',
            ])->name('cat-clave-accions.show');

            Route::put('/cat-clave-accions/{catClaveAccion}', [
                CatClaveAccionController::class,
                'update',
            ])->name('cat-clave-accions.update');

            Route::delete('/cat-clave-accions/{catClaveAccion}', [
                CatClaveAccionController::class,
                'destroy',
            ])->name('cat-clave-accions.destroy');

            Route::get(
                '/cat-ente-de-la-accions/{cat-ente-de-la-accion}/all-auditorias',
                [CatEnteDeLaAccionsAuditoriasController::class, 'index']
            )->name('cat-ente-de-la-accions.all-auditorias.index');

            Route::post(
                '/cat-ente-de-la-accions/{cat-ente-de-la-accion}/all-auditorias',
                [CatEnteDeLaAccionsAuditoriasController::class, 'store']
            )->name('cat-ente-de-la-accions.all-auditorias.store');

            Route::get('/cat-ente-de-la-accions', [
                CatEnteDeLaAccionController::class,
                'index',
            ])->name('cat-ente-de-la-accions.index');

            Route::post('/cat-ente-de-la-accions', [
                CatEnteDeLaAccionController::class,
                'store',
            ])->name('cat-ente-de-la-accions.store');

            Route::get('/cat-ente-de-la-accions/{catEnteDeLaAccion}', [
                CatEnteDeLaAccionController::class,
                'show',
            ])->name('cat-ente-de-la-accions.show');

            Route::put('/cat-ente-de-la-accions/{catEnteDeLaAccion}', [
                CatEnteDeLaAccionController::class,
                'update',
            ])->name('cat-ente-de-la-accions.update');

            Route::delete('/cat-ente-de-la-accions/{catEnteDeLaAccion}', [
                CatEnteDeLaAccionController::class,
                'destroy',
            ])->name('cat-ente-de-la-accions.destroy');

            Route::get(
                '/cat-ente-fiscalizados/{cat-ente-fiscalizado}/all-auditorias',
                [CatEnteFiscalizadosAuditoriasController::class, 'index']
            )->name('cat-ente-fiscalizados.all-auditorias.index');

            Route::post(
                '/cat-ente-fiscalizados/{cat-ente-fiscalizado}/all-auditorias',
                [CatEnteFiscalizadosAuditoriasController::class, 'store']
            )->name('cat-ente-fiscalizados.all-auditorias.store');

            Route::get('/cat-ente-fiscalizados', [
                CatEnteFiscalizadoController::class,
                'index',
            ])->name('cat-ente-fiscalizados.index');

            Route::post('/cat-ente-fiscalizados', [
                CatEnteFiscalizadoController::class,
                'store',
            ])->name('cat-ente-fiscalizados.store');

            Route::get('/cat-ente-fiscalizados/{catEnteFiscalizado}', [
                CatEnteFiscalizadoController::class,
                'show',
            ])->name('cat-ente-fiscalizados.show');

            Route::put('/cat-ente-fiscalizados/{catEnteFiscalizado}', [
                CatEnteFiscalizadoController::class,
                'update',
            ])->name('cat-ente-fiscalizados.update');

            Route::delete('/cat-ente-fiscalizados/{catEnteFiscalizado}', [
                CatEnteFiscalizadoController::class,
                'destroy',
            ])->name('cat-ente-fiscalizados.destroy');

            Route::get(
                '/cat-siglas-auditoria-especials/{cat-siglas-auditoria-especial}/all-auditorias',
                [
                    CatSiglasAuditoriaEspecialsAuditoriasController::class,
                    'index',
                ]
            )->name('cat-siglas-auditoria-especials.all-auditorias.index');

            Route::post(
                '/cat-siglas-auditoria-especials/{cat-siglas-auditoria-especial}/all-auditorias',
                [
                    CatSiglasAuditoriaEspecialsAuditoriasController::class,
                    'store',
                ]
            )->name('cat-siglas-auditoria-especials.all-auditorias.store');

            Route::get('/cat-siglas-auditoria-especials', [
                CatSiglasAuditoriaEspecialController::class,
                'index',
            ])->name('cat-siglas-auditoria-especials.index');

            Route::post('/cat-siglas-auditoria-especials', [
                CatSiglasAuditoriaEspecialController::class,
                'store',
            ])->name('cat-siglas-auditoria-especials.store');

            Route::get(
                '/cat-siglas-auditoria-especials/{catSiglasAuditoriaEspecial}',
                [CatSiglasAuditoriaEspecialController::class, 'show']
            )->name('cat-siglas-auditoria-especials.show');

            Route::put(
                '/cat-siglas-auditoria-especials/{catSiglasAuditoriaEspecial}',
                [CatSiglasAuditoriaEspecialController::class, 'update']
            )->name('cat-siglas-auditoria-especials.update');

            Route::delete(
                '/cat-siglas-auditoria-especials/{catSiglasAuditoriaEspecial}',
                [CatSiglasAuditoriaEspecialController::class, 'destroy']
            )->name('cat-siglas-auditoria-especials.destroy');

            Route::get(
                '/cat-tipo-de-auditorias/{cat-tipo-de-auditoria}/all-auditorias',
                [CatTipoDeAuditoriasAuditoriasController::class, 'index']
            )->name('cat-tipo-de-auditorias.all-auditorias.index');

            Route::post(
                '/cat-tipo-de-auditorias/{cat-tipo-de-auditoria}/all-auditorias',
                [CatTipoDeAuditoriasAuditoriasController::class, 'store']
            )->name('cat-tipo-de-auditorias.all-auditorias.store');

            Route::get('/cat-tipo-de-auditorias', [
                CatTipoDeAuditoriaController::class,
                'index',
            ])->name('cat-tipo-de-auditorias.index');

            Route::post('/cat-tipo-de-auditorias', [
                CatTipoDeAuditoriaController::class,
                'store',
            ])->name('cat-tipo-de-auditorias.store');

            Route::get('/cat-tipo-de-auditorias/{catTipoDeAuditoria}', [
                CatTipoDeAuditoriaController::class,
                'show',
            ])->name('cat-tipo-de-auditorias.show');

            Route::put('/cat-tipo-de-auditorias/{catTipoDeAuditoria}', [
                CatTipoDeAuditoriaController::class,
                'update',
            ])->name('cat-tipo-de-auditorias.update');

            Route::delete('/cat-tipo-de-auditorias/{catTipoDeAuditoria}', [
                CatTipoDeAuditoriaController::class,
                'destroy',
            ])->name('cat-tipo-de-auditorias.destroy');

            Route::get('/cat-uaas/{cat-uaa}/all-auditorias', [
                CatUaasAuditoriasController::class,
                'index',
            ])->name('cat-uaas.all-auditorias.index');

            Route::post('/cat-uaas/{cat-uaa}/all-auditorias', [
                CatUaasAuditoriasController::class,
                'store',
            ])->name('cat-uaas.all-auditorias.store');

            Route::get('/cat-uaas', [CatUaaController::class, 'index'])->name(
                'cat-uaas.index'
            );

            Route::post('/cat-uaas', [CatUaaController::class, 'store'])->name(
                'cat-uaas.store'
            );

            Route::get('/cat-uaas/{catUaa}', [
                CatUaaController::class,
                'show',
            ])->name('cat-uaas.show');

            Route::put('/cat-uaas/{catUaa}', [
                CatUaaController::class,
                'update',
            ])->name('cat-uaas.update');

            Route::delete('/cat-uaas/{catUaa}', [
                CatUaaController::class,
                'destroy',
            ])->name('cat-uaas.destroy');

            Route::get(
                '/cat-auditoria-especials/{cat-auditoria-especial}/all-auditorias',
                [CatAuditoriaEspecialsAuditoriasController::class, 'index']
            )->name('cat-auditoria-especials.all-auditorias.index');

            Route::post(
                '/cat-auditoria-especials/{cat-auditoria-especial}/all-auditorias',
                [CatAuditoriaEspecialsAuditoriasController::class, 'store']
            )->name('cat-auditoria-especials.all-auditorias.store');

            Route::get('/cat-auditoria-especials', [
                CatAuditoriaEspecialController::class,
                'index',
            ])->name('cat-auditoria-especials.index');

            Route::post('/cat-auditoria-especials', [
                CatAuditoriaEspecialController::class,
                'store',
            ])->name('cat-auditoria-especials.store');

            Route::get('/cat-auditoria-especials/{catAuditoriaEspecial}', [
                CatAuditoriaEspecialController::class,
                'show',
            ])->name('cat-auditoria-especials.show');

            Route::put('/cat-auditoria-especials/{catAuditoriaEspecial}', [
                CatAuditoriaEspecialController::class,
                'update',
            ])->name('cat-auditoria-especials.update');

            Route::delete('/cat-auditoria-especials/{catAuditoriaEspecial}', [
                CatAuditoriaEspecialController::class,
                'destroy',
            ])->name('cat-auditoria-especials.destroy');

            Route::get('/cat-entregas/{cat-entrega}/all-auditorias', [
                CatEntregasAuditoriasController::class,
                'index',
            ])->name('cat-entregas.all-auditorias.index');

            Route::post('/cat-entregas/{cat-entrega}/all-auditorias', [
                CatEntregasAuditoriasController::class,
                'store',
            ])->name('cat-entregas.all-auditorias.store');

            Route::get('/cat-entregas', [
                CatEntregaController::class,
                'index',
            ])->name('cat-entregas.index');

            Route::post('/cat-entregas', [
                CatEntregaController::class,
                'store',
            ])->name('cat-entregas.store');

            Route::get('/cat-entregas/{catEntrega}', [
                CatEntregaController::class,
                'show',
            ])->name('cat-entregas.show');

            Route::put('/cat-entregas/{catEntrega}', [
                CatEntregaController::class,
                'update',
            ])->name('cat-entregas.update');

            Route::delete('/cat-entregas/{catEntrega}', [
                CatEntregaController::class,
                'destroy',
            ])->name('cat-entregas.destroy');

            Route::get(
                '/cat-cuenta-publicas/{cat-cuenta-publica}/all-auditorias',
                [CatCuentaPublicasAuditoriasController::class, 'index']
            )->name('cat-cuenta-publicas.all-auditorias.index');

            Route::post(
                '/cat-cuenta-publicas/{cat-cuenta-publica}/all-auditorias',
                [CatCuentaPublicasAuditoriasController::class, 'store']
            )->name('cat-cuenta-publicas.all-auditorias.store');

            Route::get('/cat-cuenta-publicas', [
                CatCuentaPublicaController::class,
                'index',
            ])->name('cat-cuenta-publicas.index');

            Route::post('/cat-cuenta-publicas', [
                CatCuentaPublicaController::class,
                'store',
            ])->name('cat-cuenta-publicas.store');

            Route::get('/cat-cuenta-publicas/{catCuentaPublica}', [
                CatCuentaPublicaController::class,
                'show',
            ])->name('cat-cuenta-publicas.show');

            Route::put('/cat-cuenta-publicas/{catCuentaPublica}', [
                CatCuentaPublicaController::class,
                'update',
            ])->name('cat-cuenta-publicas.update');

            Route::delete('/cat-cuenta-publicas/{catCuentaPublica}', [
                CatCuentaPublicaController::class,
                'destroy',
            ])->name('cat-cuenta-publicas.destroy');

            Route::get(
                '/cat-siglas-tipo-acciones/{cat-siglas-tipo-accion}/all-auditorias',
                [CatSiglasTipoAccionesAuditoriasController::class, 'index']
            )->name('cat-siglas-tipo-acciones.all-auditorias.index');

            Route::post(
                '/cat-siglas-tipo-acciones/{cat-siglas-tipo-accion}/all-auditorias',
                [CatSiglasTipoAccionesAuditoriasController::class, 'store']
            )->name('cat-siglas-tipo-acciones.all-auditorias.store');

            Route::get('/cat-siglas-tipo-acciones', [
                CatSiglasTipoAccionController::class,
                'index',
            ])->name('cat-siglas-tipo-acciones.index');

            Route::post('/cat-siglas-tipo-acciones', [
                CatSiglasTipoAccionController::class,
                'store',
            ])->name('cat-siglas-tipo-acciones.store');

            Route::get('/cat-siglas-tipo-acciones/{catSiglasTipoAccion}', [
                CatSiglasTipoAccionController::class,
                'show',
            ])->name('cat-siglas-tipo-acciones.show');

            Route::put('/cat-siglas-tipo-acciones/{catSiglasTipoAccion}', [
                CatSiglasTipoAccionController::class,
                'update',
            ])->name('cat-siglas-tipo-acciones.update');

            Route::delete('/cat-siglas-tipo-acciones/{catSiglasTipoAccion}', [
                CatSiglasTipoAccionController::class,
                'destroy',
            ])->name('cat-siglas-tipo-acciones.destroy');

            Route::get('/all-auditorias', [
                AuditoriasController::class,
                'index',
            ])->name('all-auditorias.index');

            Route::post('/all-auditorias', [
                AuditoriasController::class,
                'store',
            ])->name('all-auditorias.store');

            Route::get('/all-auditorias/{auditorias}', [
                AuditoriasController::class,
                'show',
            ])->name('all-auditorias.show');

            Route::put('/all-auditorias/{auditorias}', [
                AuditoriasController::class,
                'update',
            ])->name('all-auditorias.update');

            Route::delete('/all-auditorias/{auditorias}', [
                AuditoriasController::class,
                'destroy',
            ])->name('all-auditorias.destroy');
        });
    });
