<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

// Dashboard
Route::prefix('/dashboard')
    ->name('dashboard.')
    ->middleware(['auth:sanctum', config('jetstream.auth_session'), 'verified'])
    ->group(function () {
        Route::get(
            '/cat-dgseg-efs',
            App\Livewire\Dashboard\CatDgsegEfIndex::class
        )->name('cat-dgseg-efs.index');

        Route::get(
            '/cat-dgseg-efs/create',
            App\Livewire\Dashboard\CatDgsegEfCreate::class
        )->name('cat-dgseg-efs.create');

        Route::get(
            '/cat-dgseg-efs/{catDgsegEf}',
            App\Livewire\Dashboard\CatDgsegEfEdit::class
        )->name('cat-dgseg-efs.edit');

        Route::get(
            '/cat-clave-accions',
            App\Livewire\Dashboard\CatClaveAccionIndex::class
        )->name('cat-clave-accions.index');

        Route::get(
            '/cat-clave-accions/create',
            App\Livewire\Dashboard\CatClaveAccionCreate::class
        )->name('cat-clave-accions.create');

        Route::get(
            '/cat-clave-accions/{catClaveAccion}',
            App\Livewire\Dashboard\CatClaveAccionEdit::class
        )->name('cat-clave-accions.edit');

        Route::get(
            '/cat-ente-de-la-accions',
            App\Livewire\Dashboard\CatEnteDeLaAccionIndex::class
        )->name('cat-ente-de-la-accions.index');

        Route::get(
            '/cat-ente-de-la-accions/create',
            App\Livewire\Dashboard\CatEnteDeLaAccionCreate::class
        )->name('cat-ente-de-la-accions.create');

        Route::get(
            '/cat-ente-de-la-accions/{catEnteDeLaAccion}',
            App\Livewire\Dashboard\CatEnteDeLaAccionEdit::class
        )->name('cat-ente-de-la-accions.edit');

        Route::get(
            '/cat-ente-fiscalizados',
            App\Livewire\Dashboard\CatEnteFiscalizadoIndex::class
        )->name('cat-ente-fiscalizados.index');

        Route::get(
            '/cat-ente-fiscalizados/create',
            App\Livewire\Dashboard\CatEnteFiscalizadoCreate::class
        )->name('cat-ente-fiscalizados.create');

        Route::get(
            '/cat-ente-fiscalizados/{catEnteFiscalizado}',
            App\Livewire\Dashboard\CatEnteFiscalizadoEdit::class
        )->name('cat-ente-fiscalizados.edit');

        Route::get(
            '/cat-siglas-auditoria-especials',
            App\Livewire\Dashboard\CatSiglasAuditoriaEspecialIndex::class
        )->name('cat-siglas-auditoria-especials.index');

        Route::get(
            '/cat-siglas-auditoria-especials/create',
            App\Livewire\Dashboard\CatSiglasAuditoriaEspecialCreate::class
        )->name('cat-siglas-auditoria-especials.create');

        Route::get(
            '/cat-siglas-auditoria-especials/{catSiglasAuditoriaEspecial}',
            App\Livewire\Dashboard\CatSiglasAuditoriaEspecialEdit::class
        )->name('cat-siglas-auditoria-especials.edit');

        Route::get(
            '/cat-tipo-de-auditorias',
            App\Livewire\Dashboard\CatTipoDeAuditoriaIndex::class
        )->name('cat-tipo-de-auditorias.index');

        Route::get(
            '/cat-tipo-de-auditorias/create',
            App\Livewire\Dashboard\CatTipoDeAuditoriaCreate::class
        )->name('cat-tipo-de-auditorias.create');

        Route::get(
            '/cat-tipo-de-auditorias/{catTipoDeAuditoria}',
            App\Livewire\Dashboard\CatTipoDeAuditoriaEdit::class
        )->name('cat-tipo-de-auditorias.edit');

        Route::get(
            '/cat-uaas',
            App\Livewire\Dashboard\CatUaaIndex::class
        )->name('cat-uaas.index');

        Route::get(
            '/cat-uaas/create',
            App\Livewire\Dashboard\CatUaaCreate::class
        )->name('cat-uaas.create');

        Route::get(
            '/cat-uaas/{catUaa}',
            App\Livewire\Dashboard\CatUaaEdit::class
        )->name('cat-uaas.edit');

        Route::get(
            '/cat-auditoria-especials',
            App\Livewire\Dashboard\CatAuditoriaEspecialIndex::class
        )->name('cat-auditoria-especials.index');

        Route::get(
            '/cat-auditoria-especials/create',
            App\Livewire\Dashboard\CatAuditoriaEspecialCreate::class
        )->name('cat-auditoria-especials.create');

        Route::get(
            '/cat-auditoria-especials/{catAuditoriaEspecial}',
            App\Livewire\Dashboard\CatAuditoriaEspecialEdit::class
        )->name('cat-auditoria-especials.edit');

        Route::get(
            '/cat-entregas',
            App\Livewire\Dashboard\CatEntregaIndex::class
        )->name('cat-entregas.index');

        Route::get(
            '/cat-entregas/create',
            App\Livewire\Dashboard\CatEntregaCreate::class
        )->name('cat-entregas.create');

        Route::get(
            '/cat-entregas/{catEntrega}',
            App\Livewire\Dashboard\CatEntregaEdit::class
        )->name('cat-entregas.edit');

        Route::get(
            '/cat-cuenta-publicas',
            App\Livewire\Dashboard\CatCuentaPublicaIndex::class
        )->name('cat-cuenta-publicas.index');

        Route::get(
            '/cat-cuenta-publicas/create',
            App\Livewire\Dashboard\CatCuentaPublicaCreate::class
        )->name('cat-cuenta-publicas.create');

        Route::get(
            '/cat-cuenta-publicas/{catCuentaPublica}',
            App\Livewire\Dashboard\CatCuentaPublicaEdit::class
        )->name('cat-cuenta-publicas.edit');

        Route::get(
            '/cat-siglas-tipo-acciones',
            App\Livewire\Dashboard\CatSiglasTipoAccionIndex::class
        )->name('cat-siglas-tipo-acciones.index');

        Route::get(
            '/cat-siglas-tipo-acciones/create',
            App\Livewire\Dashboard\CatSiglasTipoAccionCreate::class
        )->name('cat-siglas-tipo-acciones.create');

        Route::get(
            '/cat-siglas-tipo-acciones/{catSiglasTipoAccion}',
            App\Livewire\Dashboard\CatSiglasTipoAccionEdit::class
        )->name('cat-siglas-tipo-acciones.edit');
    });

// API
Route::prefix('/api')
    ->name('api.')
    ->middleware(['auth:sanctum', config('jetstream.auth_session'), 'verified'])
    ->group(function () {});

// Site
Route::prefix('/')->group(function () {});

// Filament Panel
Route::prefix('/panel')
    ->name('panel.')
    ->group(function () {});
